version: "3"
services:
  angular-app:
    image: angular-app
    stdin_open: true
    ports: 
      - "4200:4200"
    networks:
      - mern-app
  api-server:
    image: api-server
    ports:
      - "5000:5000"
    networks:
      - mern-app
    depends_on:
      - mongo
      - redis
  mongo:
    image: mongo:3.6.19-xenial
    ports:
      - "27017:27017"
    networks:
      - mern-app
    volumes:
      - mongo-data:/data/db
  redis:
    image:redis:latest
    ports: - "6379"
    networks:
      - mern-app
    volumes:
      - redis-data:/redis/data/db
networks:
  mern-app:
    driver: bridge
volumes:
  mongo-data:
    driver: local
  redis:
    driver: local